### ISSUE TITLE
Page number more than 1 keeps loading for listing of elements

### ISSUE THREAD

**Issue by ESiggstedt** [makerspace/makeradmin#444] opened 2024-01-15 12:40 UTC
**Problem:** When selecting page 2 or more, when having more than 25 elements to list, the page just keeps loading.

**Background/Description:** The problem was solved for some lists such as category list by using CollectionNavigation. But the problem remains for lists written in scripts with .tsx format. The same solution doesn't seem to be directly applicable.

**At least those scripts with lists have this problem:**

- QuizList.tsx
- QuestionList.tsx

**Comment by HalfVoxel** [comment] 2024-01-15 12:51
Duplicate of #415?

**Closed** 2024-01-20 10:49 UTC
Labels: bug, admin
